### ISSUE TITLE
RuntimeError: pStyle: Title

### ISSUE THREAD

**Issue by junxu-ai** [coldfix/doc2md#9]
Hi, 

When i use "!python -m docx2md /content/temp.docx /content/temp.md" to convert the docx into MD in colab, it gives the following error:

Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.10/dist-packages/docx2md/__main__.py", line 104, in <module>
    main()
  File "/usr/local/lib/python3.10/dist-packages/docx2md/__main__.py", line 27, in main
    md_text = convert(docx, target_dir, media, args.md_table)
  File "/usr/local/lib/python3.10/dist-packages/docx2md/__main__.py", line 94, in convert
    return converter.convert()
  File "/usr/local/lib/python3.10/dist-packages/docx2md/converter.py", line 36, in convert
    self.parse_node(of, body)
  File "/usr/local/lib/python3.10/dist-packages/docx2md/converter.py", line 58, in parse_node
    self.parse_p(of, child)
  File "/usr/local/lib/python3.10/dist-packages/docx2md/converter.py", line 205, in parse_p
    raise RuntimeError("pStyle: " + style)
RuntimeError: pStyle: Title

-----------
I also attached the docx file as a reference. 

[temp.docx](https://github.com/coldfix/doc2md/files/12396218/temp.docx)

Thanks.

**Comment by junxu-ai** [comment]
paste into the wrong place.
